export const registerInputs = [
    {
        id:1,
        type:'text',
        name:'username',
        placeholder:'username',
        label:'username',
        required:true
    },
    {
        id:2,
        type:'email',
        name:'email',
        placeholder:'email',
        label:'email',
        required:true
    },
    {
        id:3,
        type:'password',
        name:'password',
        placeholder:'password',
        label:'password',
        required:true
    }
]